site_name: Wiki of the IMAGeS Team
site_description: A collection of tips and tricks for students (but not only) of the IMAGeS team.
site_author: Luc Vedrenne
site_url: https://listindexoutofrange.github.io/WikiImages/
repo_url: https://github.com/ListIndexOutOfRange/WikiImages
repo_name: WikiImagesTeam
# No edit button, as some of our pages could be in docs via symlink, so it's impossible for them
# all to be accurate.
edit_uri: ""
strict: true  # Don't allow warnings during the build process


# _______________________________________________________________________________________________ #

nav:
    - Home: 'index.md'
    - 'contributing.md'
    - External GPUs access:
        - MIV servers: gpus_access/miv.md
        - HPC: gpus_access/hpc.md
    # - Section: 'section.md'
    # - Notebooks:
    #     - Test integration: 'notebook.ipynb'
    # - Full API:
    #     - Submodule: api/dummy.md

# _______________________________________________________________________________________________ #

theme:
    name: material
    features:
        - content.tabs.link
        - content.code.annotate
        # - navigation.tabs
        - navigation.sections # Sections are included in the navigation on the left.
        # navigation.expand
        - navigation.instant # XHR dispatching without full page reloading
        - navigation.tracking # Update URL with active anchor
        - navigation.top # Back to top button when scrolling down
        # Table of contents is integrated on the left; does not appear separately on the right.
        # - toc.integrate
        - toc.follow  # active anchor is always visible  
        - header.autohide  # header disappears as you scroll
    palette:
        # Light mode / dark mode
        # We deliberately don't automatically use `media` to check a user's preferences. We default to
        # light mode as (a) it looks more professional, and (b) is more obvious about the fact that
        # it offers a (dark mode) toggle.
        - scheme: default
          primary: white
          accent: amber
          toggle:
             icon: material/weather-night
             name: Switch to dark mode
        - scheme: slate
          primary: black
          accent: amber
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode
    icon:
        admonition:
            note: octicons/tag-16
            abstract: octicons/checklist-16
            info: octicons/info-16
            tip: octicons/squirrel-16
            success: octicons/check-16
            question: octicons/question-16
            warning: octicons/alert-16
            failure: octicons/x-circle-16
            danger: octicons/zap-16
            bug: octicons/bug-16
            example: octicons/beaker-16
            quote: octicons/quote-16
        repo: fontawesome/brands/github  # GitHub logo in top right
        logo: "material/circle-opacity"  # Equinox logo in top left
    favicon: "_static/favicon.png"
    # Bellow is commented out because it is not required in this particular project.
    # custom_dir: "docs/_overrides"  # Overriding part of the HTML


# _______________________________________________________________________________________________ #

extra_javascript: 
    # The below three make MathJax work, see:
    # https://squidfunk.github.io/mkdocs-material/reference/mathjax/
    - _static/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


# _______________________________________________________________________________________________ #

extra_css:
    - _static/custom_css.css


# _______________________________________________________________________________________________ #

markdown_extensions:
    - def_list
    - attr_list
    - md_in_html
    - admonition
    - codehilite
    - footnotes
    # ------------------ #
    - pymdownx.details
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.inlinehilite
    # ------------------ #
    - pymdownx.tabbed:
        alternate_style: true 
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.snippets:  # Include one Markdown file into another
        base_path: docs
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    # ------------------ #
    - toc:
        title: On this page
        permalink: "¤"  # Adds a clickable permalink to each section heading
        toc_depth: 4

# _______________________________________________________________________________________________ #

plugins:
    - search  # default search plugin; needs manually re-enabling when using any other plugins
    - autorefs  # Cross-links to headings
    # Bellow is commented out because it is not required in this particular project.
    # - include_exclude_files:
    #     include:
    #         - ".htaccess"
    #     exclude:
    #         - "_overrides"
    - mknotebooks  # Jupyter notebooks
    - mkdocstrings:
        handlers:
            python:
                setup_commands:
                    - import pytkdocs_tweaks
                    - pytkdocs_tweaks.main()

                selection:
                    inherited_members: true  # Allow looking up inherited methods
                rendering:
                    show_root_heading: true  # actually display anything at all...
                    show_root_full_path: true  # display "module.function" not just "function"
                    show_if_no_docstring: true
                    show_signature_annotations: true
                    show_source: false  # don't include source code
                    # Order methods according to their order of definition in the source code,
                    # not alphabetical order.
                    members_order: source  
                    heading_level: 4
    - encryptcontent:
        use_secret: true
        title_prefix: '' # '[Protected] '
        summary: 'This content is not public'
        placeholder: 'Please provide your password and press ENTER'
        decryption_failure_message: 'Invalid password.'
        encryption_info_message: 'You must be a member of the IMAGeS team in order to have access to this page.'
