name: ci 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3.0.2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Deploy
        run: |
          pip install -r ./docs/requirements.txt 
          mkdocs gh-deploy --force
      - name: Test password injection
        run: python .github/inject.py --secret "${{ secrets.PASSWORD }}"